function fct(R,Vcc,Vi,y,c)

F1=figure('Name','Amplificator in putere de clasa B - Cronograme',...
         'Units','normalized',...
         'NumberTitle','off',...
         'Position',[0.1 0.1 0.8 0.8],...
         'color','#ABCDEF');
B1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.0 0.93 1 0.05],...
              'fontweight','bold',...
              'Fontsize',16,...
              'foregroundcolor','k',...
              'Background','#ABCDEF',...
              'String','Amplificator in putere de clasa B: cronograme');
          
%valori
limitator=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.8 0.2 0.25 0.05],...
              'Background','#ABCDEF',...
              'Visible', 'off');
          
R1=uibuttongroup('ForegroundColor','black',...
                 'Title','Valori:',...
                 'FontSize',10,...
                 'Fontweight','bold',...
                 'Background','#99cccc',...
                 'TitlePosition','centertop',...
                 'Tag','radiobutton',...
                 'Position',[0.65 0.15 0.2 0.25]);

Bt1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.7 0.3 0.2],...
              'Background','w',...
              'String','R',...
              'Parent',R1);
Be1=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.7 0.3 0.2],...
              'String',R,...
              'Parent',R1,...
              'Callback','R=str2num(get(gco,"string")),close, fct(R,Vcc,Vi,y,c)');
Bt2=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.4 0.3 0.2],...
              'Background','w',...
              'String','Vcc',...
              'Parent',R1);
Be2=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.4 0.3 0.2],...
              'String',Vcc,...
              'Parent',R1,...
              'Callback','Vcc=str2num(get(gco,"string")),close,fct(R,Vcc,Vi,y,c)');
          
Bt3=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.1 0.3 0.2],...
              'String','Vi',...
              'Background','w',...
              'Parent',R1);
Be3=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.1 0.3 0.2],...
              'String',Vi,...
              'Parent',R1,...
              'Callback','Vi=str2num(get(gco,"string")),close, fct(R,Vcc,Vi,y,c)');
if(R<=0)
     R=10;
     set(limitator,'String','R nu poate fi mai mica ca 0!','Visible','on');
end
if(Vi>Vcc)
    Vi=Vcc;
    set(limitator,'String','Vi nu poate depasi Vcc','Visible','on');
end



%optiuni

Br1=uicontrol('Style','radiobutton',...
             'Units','normalized',...
             'Position',[0.4 0.8 .15 0.1],...
             'Value',0,...
             'String','Afiseaza semnalul de intrare',...
             'Fontsize',10,...
             'Background','#99cccc',...
             'Callback','y=1,close,fct(R,Vcc,Vi,y,c)');
Br2=uicontrol('Style','radiobutton',...
             'Units','normalized',...
             'Position',[0.4 0.7 .15 0.1],...
             'Value',0,...
             'String','Afiseaza CSTV',...
             'Fontsize',10,...
             'Background','#99cccc',...
             'Callback','y=2,close,fct(R,Vcc,Vi,y,c)');
Br3=uicontrol('Style','radiobutton',...
             'Units','normalized',...
             'Position',[0.4 0.6 .15 0.1],...
             'Value',0,...
             'String','Afiseaza puterea de iesire',...
             'Fontsize',10,...
             'Background','#99cccc',...
             'Callback','y=3,close,fct(R,Vcc,Vi,y,c)');
         
%timpul

T=1./1000;      
w=2.*pi.*1000;         
t=0:T/100:2 *T; 
vi=Vi.*sin(w.*t);

%iesirea

for i=1:length(t)
    if(vi(i)<-0.7)
        vout(i)=vi(i)+0.7;
    else
        if(vi(i)>0.7)
            vout(i)=vi(i)-0.7;
        else
            vout(i)=0;
        end
    end
end
subplot('Position',[0.05 0.60 0.30 0.3]);
plot(t,vout,'-*r')
grid on;
title('Tensiunea de iesire')
xlabel('timp [s]');         
ylabel('Amplitudine [V]');  
if(y==1)
    set(Br1,'Value',1);
    hold on
    title('Tensiune de intrare si de iesire');
    plot(t,vi,'-og')
    legend('vout','vi');
end


%curentul

Bt4=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.4 0.35 0.2 0.04],...
              'Fontsize',12,...
              'Background','#ABCDEF',...
              'String','Alege curentul care se va afisa');

PP=uicontrol('Style','PopupMenu',...
            'Units','normalized',...
            'Position', [0.4 0.3 0.2 0.05],...
            'value',c,...
            'Fontsize',12,...
            'String','Io|Ic1|Ic2',...
            'Callback','c=(get(gco,"value"));close;fct(R,Vcc,Vi,y,c)');
        
if(Vi==Vcc)
	Vomax=(Vcc-0.2);
else
    Vomax=Vi-0.7;
end
vomax=Vomax.*sin(w*t);
for i=1:length(t)
    if(vi(i)<-0.7)
        vomax(i)=vi(i)+0.7;
    else
        if(vi(i)>0.7)
            vomax(i)=vi(i)-0.7;
        else
            vomax(i)=0;
        end
    end
end

io=vomax./R;
io1=abs(io);
ic1=(io+io1)/2;
ic2=(io1-ic1);
subplot('Position',[0.05 0.1 0.30 0.3]);
switch c
    case 1
        plot(t,io,'.r');
        title('Curentul de iesire');
    case 2
        plot(t,ic1,'om');
        title('Curentul din T1');
    case 3
        plot(t,ic2,'*b');
        title('Curentul din T2');
end
grid on;
xlabel('Timp [s]');
ylabel('Amplitudine [A]');

%CSTV

if(y==2)
    set(Br2,'Value',1);
    subplot('position',[0.65 0.6 0.2 0.3])
    plot(vi,vout)
    title('CSTV')
    xlabel('vi')
    ylabel('vout')
grid on;
end

%Puterea

if(y==3)
    set(Br3,'Value',1);
    subplot('Position',[0.65 0.6 0.30 0.3]);
    po=vomax.^2./R
    plot(t,po)
    grid on
    title('Puterea de iesire');
    xlabel('timp [s]');
    ylabel('Amplitudine [W]');
end

%close
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'String','Inapoi',...
    'Position',[0.85 0.05 0.1 0.05],...
    'Backgroundcolor','#ffcc66',...
    'Fontsize',10,...
    'Callback','close')