function fct2(R,Vcc,Vi,value)

F1=figure('Name','Amplificator in putere de clasa B - Ecuatii',...
         'Units','normalized',...
         'NumberTitle','off',...
         'Position',[0.1 0.1 0.8 0.8],...
         'color','#ABCDEF');
B=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.0 0.9 1 0.05],...
              'fontweight','bold',...
              'Fontsize',16,...
              'foregroundcolor','k',...
              'Background','#ABCDEF',...
              'String','Amplificator in putere de clasa B: ecuatii');
Br=uicontrol('Style','checkbox',...
             'Units','normalized',...
             'Position',[0.15 0.75 .2 .05],...
             'Background','w',...
             'Fontsize',10,...
             'Value',value,...
             'String','Amplitudine maxima (Vo=Vcc)',...
             'Callback','value=get(gco,''value''),close,fct2(R,Vcc,Vi,value)');
R1=uibuttongroup('Visible','on',...
                 'ForegroundColor','black',...
                 'Title','Valori:',...
                 'FontSize',10,...
                 'Background','#99cccc',...
                 'TitlePosition','centertop',...
                 'Tag','radiobutton',...
                 'Position',[0.1 0.4 0.3 0.3]);
R2=uibuttongroup('Visible','on',...
                 'ForegroundColor','black',...
                 'FontSize',10,...
                 'Background','#99cccc',...
                 'TitlePosition','centertop',...
                 'Tag','radiobutton',...
                 'Position',[0.5 0.4 0.3 0.3]);
%calcule
if(Br.Value==true)
    Po=(Vcc^2)/(2*R);
    Pal=2*(Vcc^2)/(pi*R);
    randament=(pi/4)*100;
    set(R2,'Title','Putere si randament maxim');
else
    Po=(Vi-0.7)^2/(2*R);
    Pal=2*(Vi-0.7)^2/(pi*R);
    randament=(((Vi-0.7)/Vcc)*(pi/4))*100;
    set(R2,'Title','Putere si randament');
end

%valori   

Bt1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.7 0.3 0.2],...
              'String','R',...
              'Background','w',...
              'Parent',R1);
Be1=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.7 0.3 0.2],...
              'String',R,...
              'Parent',R1,...
              'Callback','R=str2num(get(gco,"string")),close, fct2(R,Vcc,Vi,value)');
Bt2=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.4 0.3 0.2],...
              'String','Vcc',...
              'Background','w',...
              'Parent',R1);
Be2=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.4 0.3 0.2],...
              'String',Vcc,...
              'Parent',R1,...
              'Callback','Vcc=str2num(get(gco,"string")),close,fct2(R,Vcc,Vi,value)');
Bt3=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.1 0.3 0.2],...
              'String','Vi',...
              'Background','w',...
              'Parent',R1);
Be3=uicontrol('Style','edit',...
              'Units','normalized',...
              'Position',[0.5 0.1 0.3 0.2],...
              'String',Vi,...
              'Parent',R1,...
              'Callback','Vi=str2num(get(gco,"string")),close, fct2(R,Vcc,Vi,value)');

          
 %Putere    

Bt1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.7 0.3 0.2],...
              'String','Po=(Vo^2)/(2*R)',...
              'Background','w',...
              'Parent',R2);
Be1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.5 0.7 0.3 0.2],...
              'String',Po,...
              'Background','w',...
              'Parent',R2,...
              'Callback','Po=str2num(get(gco,"string")),close, fct2(R,Vcc,Vi,value)');
Bt2=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.4 0.3 0.2],...
              'String','Pal=2*(Vo^2)/(pi*R)',...
              'Background','w',...
              'Parent',R2);
Be2=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.5 0.4 0.3 0.2],...
              'String',Pal,...
              'Background','w',...
              'Parent',R2,...
              'Callback','Pal=str2num(get(gco,"string")),close,fct2(R,Vcc,Vi,value)');
Bt3=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.2 0.1 0.3 0.2],...
              'String','randament=Po/Pal',...
              'Background','w',...
              'Parent',R2);
Be3=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.5 0.1 0.3 0.2],...
              'String',randament,...
              'Background','w',...
              'Parent',R2,...
              'Callback','randament=str2num(get(gco,"string")),close, fct2(R,Vcc,Vi,value)');
          
%close         
Bp=uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'String','Inapoi',...
    'Position',[0.85 0.05 0.1 0.05],...
    'Backgroundcolor','#ffcc66',...
    'Fontsize',10,...
    'Callback','close')