close all;
clear all;
R=10;
Vcc=20;
Vi=4;
value=0;
y=1;
c=1;
x='Bibliografie.pdf';
F=figure('Name','Amplificator in putere de clasa B ',...
         'Units','normalized',...
         'NumberTitle','off',...
         'Position',[0.1 0.1 0.8 0.8],...
         'color','#bfbfbf');
B1=uicontrol('Style','text',...
              'Units','normalized',...
              'Position',[0.0 0.93 1 0.05],...
              'fontweight','bold',...
              'Fontsize',20,...
              'foregroundcolor','k',...
              'Background','#bfbfbf',...
              'String','Amplificator in putere de clasa B')
%imagine
y=imread('clasaB.jpg');
subplot('Position',[0 0.1 1 0.8]);
imshow(y);
f=uimenu('Label','Documentatie','foregroundcolor','r');
f1=uimenu(f,'Label','Amplificator in putere de clasa B','Separator','on');
f1_1=uimenu(f1,'Label','Cronograme','Callback','fct(R,Vcc,Vi,y,c)');
f1_2=uimenu(f1,'Label','Ecuatii','Callback','fct2(R,Vcc,Vi,value)');
f2=uimenu(f,'Label','Bibliografie','Callback','fct3(x)');
f3=uimenu(f,'Label','Close','Callback','close');